### ISSUE TITLE
怎么解决我的这个问题

### ISSUE THREAD

**Issue by cctvbtv123456** [xuezhulian/classunref#2]
/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'classunref.py': [Errno 2] No such file or directory

**Comment by cctvbtv123456** [comment]
醉了，文件名字不一样，classunrefs.py，少个s

**Comment by xuezhulian** [comment]
抱歉，已经更正

**Comment by cctvbtv123456** [comment]
/Users/justin/Library/Developer/Xcode/DerivedData/QXWisdomClassPt-hhtxsdicoqncoveactqzdpcetpav/Build/Products/Debug-iphoneos/QXWisdomClassPt.app,输出这个之后一直不动，怎么回事

**Comment by xuezhulian** [comment]
没有打印出 Get class list pointers... ？

**Comment by cctvbtv123456** [comment]
没有------------------ 原始邮件 ------------------
发件人: "xuezhulian"<notifications@github.com>
发送时间: 2019年8月23日(星期五) 上午10:07
收件人: "xuezhulian/classunref"<classunref@noreply.github.com>;
抄送: "cctvbtv123456"<1272524311@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuezhulian/classunref] 怎么解决我的这个问题 (#2)



没有打印出 Get class list pointers... ？
 
&mdash;

**Comment by cctvbtv123456** [comment]
没有啊

**Comment by xuezhulian** [comment]
你更新试试，我之前传的脚本有问题

**Comment by cctvbtv123456** [comment]
方便加个联系方式吗

**Comment by xuezhulian** [comment]
头像就是我微信

**Comment by s1lence2012** [comment]
> 没有打印出 Get class list pointers... ？
有打印，然后就这样了：
Error:class list pointers null
