### ISSUE TITLE
Error:class symbols null

### ISSUE THREAD

**Issue by xl20071926** [xuezhulian/classunref#3]
Error:class symbols null
请问下返回这个结果是什么问题？能否指点一下

**Comment by yuanxinliang** [comment]
同样遇到+1

**Comment by tellmebigcat** [comment]
+1，看来这个问题还挺常见的，希望能够解决一哈~~

**Comment by xuezhulian** [comment]
32位的系统不行，没有适配过。

**Comment by xuezhulian** [comment]
可以手动用 nm -nm app目录里面的可执行文件路径 看下 _OBJC_CLASS_ 是个什么格式，为啥这个正则 (\w{16}) .* _OBJC_CLASS_\$_(.+) 匹配不到。

**Comment by tellmebigcat** [comment]
我这边又试了一下，发现直接工程内用products文件夹下面的.app文件就可以了，我之前不行是因为使用的是Xcode执行product->archive后的xcarchive包内的.app文件了~

**Comment by tellmebigcat** [comment]
实测用取__DATA __objc_classrefs和__DATA __objc_classlist差集的方式效率其实是很低的，因为很多类文件在是.m文件内引入的，没有在.h文件中引入，所以不会出现在DATA.objcclassrefs段，自然就会出现在差集里面，然后在二次确认差集内包含的类时，发现99%以上都是有用的类。对于清理无用类来说，帮助甚微

**Comment by xuezhulian** [comment]
@tellmebigcat "因为很多类文件在是.m文件内引入的，没有在.h文件中引入" 理解错了？这里跟头文件引用没有关系。我又测试了一遍 init 方法走了就会出现在 __objc_classlist 这个 section 里面。另外这这只是 OC 静态分析，对动态调用无效。

**Comment by xuezhulian** [comment]
还发现一个问题 target 选择 iOS13 的时候获取不到数据，选择 iOS10 就可以了，有时间再查一下。

**Comment by tellmebigcat** [comment]
> 这这只是 OC 静态分析，对动态调用无

不是动态调用，我这边的意思是不会出现在 __objc_classrefs，但是会出现在__objc_classlist，然后取两者差集的话就会被列为“无用类”。

**Comment by xuezhulian** [comment]
" init 方法走了就会出现在 __objc_classlist 这个 section 里面" 这里描述错了是 __objc_classrefs
