### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by freedomct** [xuezhulian/classunref#4]
python3 环境 raw_input 和 print 问题 没办法提交分支 所有麻烦作者看下了

**Comment by freedomct** [comment]
python3 环境  raw_input   和 print 问题 没办法提交分支 所有麻烦作者看下了

**Comment by kshitij1235** [comment]
Can i get the translation in English so i can help you ☺️☺️☺️

**Comment by xuezhulian** [comment]
done
